### ISSUE TITLE
Follow request notification is broken 

### ISSUE THREAD

**Issue by elenners** [dNitza/mercury-issues#1]
Hello! I just started using your app and love it so far. I did run into an issue with follow requests as my account is locked. See screenshot: It doesn't recognize what they are. I was able to cross-reference my notifications on the website to figure out that's what it was. 

![1AF3C941-5AE5-4A9F-A4C8-80F69A436A46](https://user-images.githubusercontent.com/63966511/85202431-07134f80-b2cc-11ea-9869-15c749751b9f.jpeg)

**Comment by dNitza** [comment]
Hey there! Thanks for reporting this. I do have handling follow requests on my list for a future release but totally missed the notification type :) I shall bump this up to be a part of the next release!

**Comment by dNitza** [comment]
Should be resolved in the latest update :)
