### ISSUE TITLE
Boosts are not indicated to VoiceOver users.

### ISSUE THREAD

**Issue by rkingett** [dNitza/mercury-issues#10]
This is a very small thing, but after I boost a Toot, and then go back and review my home timeline later, I forgot which Toots I boosted, and there is currently no indication that a Toot has been boosted by me or not.

Could either of the below work as a solution?

1. Make the boost action change to, unboost, if a Toot has been previously boosted?
2. Put a small message at the start of the item, before the name, that says, "boosted,"

I like 2 the best because I can just flick through timelines quicker that way.

I'd ultimately like VoiceOver to tell me if I previously boosted a Toot before, or not, when scrolling through timelines.

## Device information.

iPhone model. SE 2020.

OS: 13.6.

**Comment by dNitza** [comment]
Hey hey :) Yep! This is something else that is coming in the next beta.

**Comment by rkingett** [comment]
While this is technically fixed, there is still a bug when related to this happening. Maybe it's because the lack of refreshing?

When I boost a Toot through the custom action, I have to do it twice to get the action to change to, unboost. Is that because the screen isn't refreshing?

If I navigate away from the Toot I just boosted, then back, I don't hear the Boosted announcement. Again, I'm thinking because the app hasn't refreshed the page. Thoughts?

**Comment by dNitza** [comment]
Ohhh yes! You're right 🤦 — I'll get that in to the next release :)

**Comment by rkingett** [comment]
I'm thinking this can be closed. If they are not indicated in threads, open this up again.
