### ISSUE TITLE
VoiceOver focus when reading threads is glitchy

### ISSUE THREAD

**Issue by rkingett** [dNitza/mercury-issues#12]
When reading threads, it takes more than one swipe to navigate forward in a thread. Navigating in reverse, looking at threads, appears to have the same issue.

## To Reproduce

1. With VoiceOver enabled, navigate to a thread view, not the home or notification timeline.
2. Start at the first toot in a thread.
3. Navigate forward by swiping right. Backward by swiping left.

## Expected behavior

VoiceOver should treat each toot in the thread as a single element.

## Device information.

IOS 13.6.

iPhone SE 2020.

**Comment by dNitza** [comment]
I have not been able to replicate this so I shall close for now, but if it's still occurring let me know or reopen this issue and I'll look in to it further :)
