### ISSUE TITLE
When replying to someone, edit cursor starts at beginning.

### ISSUE THREAD

**Issue by rkingett** [dNitza/mercury-issues#13]
When replying to someone, the edit cursor starts at the beginning of the edit field, not at the end, past the usernames. I am assuming this is a general bug, but I am unsure. It happens when sending a reply or DM with VO turned on.

**To Reproduce**

1. Enable VoiceOver.
2. Reply to someone or DM someone.

**Expected behavior**
The cursor should start at the end, past the usernames mentioned.

iPhone information.

iPhone: SE 2020.

IOS 13.6.

**Comment by dNitza** [comment]
Hmm I think this might be a VoiceOver thing. The cursor is at the end past the user names being mentioned, but the announcement says it is at the start. It could also be how I am adding the usernames to the text field, I shall investigate!
