### ISSUE TITLE
Accessibility: Add an option to speak usernames last for VoiceOver

### ISSUE THREAD

**Issue by pitermach** [dNitza/mercury-issues#16]
**Is your feature request related to a problem? Please describe.**
Currently, Mercury speaks a user's display and screen name directly after each other, which is I guess also how it's displayed visually. However, in my opinion this slows down navigation for speech, but especially braille display users. In 99% of all cases, what you'd care about the most when reading a post is someone's name, and the content of the post. Having to hear their screen name every time as well, especially if they're on a different instance, can get a bit tedious. This is even more apparent if using a braille display, which can only display a limited number of characters at a time. The one I'm using with my phone most of the time is 14-characters long. SO as an example if we take both my display name and full screen name, Piotr Machacz pitermach@mastodon.social, that takes up 39 characters, so I'd have to scroll it 2, probably in practice 3 times to actually get to the toot content.

**Describe the solution you'd like**
Since Mercury already has an accessibility section in its settings, presenting the username last could just be a toggle there, this would make people on both sides of the fence happy if someone prefers the current behavior

**Additional context**
Presenting the username last for screen readers is being done in a number of other clients, including the official Mastodon web app, Pinafore, Tusky on Android and Toot! on iOS. So it's a format that seems to be preferred by users.

**Comment by rkingett** [comment]
Absolutely love this idea. :) This could be changed in the settings with a toggle.

**Comment by dNitza** [comment]
Yeah this is a great idea!! I'll pop this in to the next build :)

**Comment by pitermach** [comment]
I just got the new build this morning. Thanks for implementing this, Mercury is very quickly becoming my favorite client! :)

**Comment by dNitza** [comment]
No worries! Thanks for your suggestions :)
