### ISSUE TITLE
Accessibility: An idea to redesign the actions order customisation interface

### ISSUE THREAD

**Issue by pitermach** [dNitza/mercury-issues#17]
First of all I absolutely love the level of customisation in this app. Having the ability to change the order of custom actions around is really cool. I have a suggestion that could speed up the process.

At the moment, you need to press on each action slot and change the action in a list. This means that, if you for example want to swap some actions around, you need to press on and change both of them, otherwise you'll end up with duplicates. A better way to do this I think would be to use the native iOS interface for a reorderable list, I'm not sure what it's officially called. You can find an example of this if you go to Settings>Accessibility>VoiceOver>Rotor. You have a rather large list of things you can put on the rotor, with a button on the right of each of them that can be held down to move an item up or down. If you press it and start moving, VoiceOver provides feedback what gets moved where so you always know what you're doing, and if you really don't want to manually drag things around each item also provides a "move down" and "move up" custom action so you can also move things that way.

**Comment by rkingett** [comment]
[This may be what you are looking for.](https://developer.apple.com/documentation/uikit/uicollectionviewdiffabledatasourcereorderinghandlers?language=en)

I'm not sure why it's saying it's in 14+ though because this is in many apps today.

**Comment by dNitza** [comment]
Oh awesome :) yeah this would be much much nicer. I wasn't sure if it would be accessible at all. Thanks for pointing this out, I'll look at getting this out in to the next build!

**Comment by rkingett** [comment]
Anything native IOS is accessible to VoiceOver and people using speech commands. I couldn't find the version that works for 13 though so you may need to look through documentation.

**Comment by pitermach** [comment]
I just got the new build, and this new interface is so so much better. Thanks!

One minor thing that may need cleaning up though is that you can drag the actions outside the list and into the other controls in the accessibility settings.
