### ISSUE TITLE
Favorites won't update

### ISSUE THREAD

**Issue by elenners** [dNitza/mercury-issues#2]
The favorites tab unfortunately is stuck on the first load. Screenshot attached for what it does when you pull down to load more. It just stays like that and doesn't do anything. 

![D7F1A9B5-85A4-49EC-864E-467A89B45158](https://user-images.githubusercontent.com/63966511/85763992-cf951080-b6da-11ea-9a8f-9f0eb7401a5e.jpeg)

**Comment by dNitza** [comment]
Oh weird! I have not seen favourites not come in before. If there are new favourites to be received they should be appearing there — I will look in to it :)

The pull to refresh thing leaving the content half way down the page is an issue that _should_ be fixed as part of the next release.

Thank you again for these reports, they're super helpful and much appreciated.

**Comment by dNitza** [comment]
I _think_ this has been resolved in the latest update
