### ISSUE TITLE
Text cut out

### ISSUE THREAD

**Issue by Mennaruuk** [dNitza/mercury-issues#20]
**Describe the bug**
Some text is cut out.

**To Reproduce**
Go to Timelines

**Expected behavior**
Text should appear without its being cut.

**Screenshots**
![3F6EAA0D-311F-4879-B8ED-CF320477090A](https://user-images.githubusercontent.com/52135169/111097231-83fbee80-8517-11eb-9618-efd99de30eec.jpeg)

**iPhone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 14.4.1

**Additional context**
Your app rocks!

**Comment by dNitza** [comment]
Hey @Mennaruuk! Thanks so much for letting me know :) I know exactly what this is and I'll get it fixed up for the next release 🙏

**Comment by Mennaruuk** [comment]
thank you so much!!!
