### ISSUE TITLE
Usage agreement should be improved

### ISSUE THREAD

**Issue by wadoli** [dNitza/mercury-issues#22]
**Describe the bug**
The usage agreement forces the user to agree to a text that isn't clear and concise, especially the first paragraph. Also the GitHub-Link to blocked instances doesn't work.

**To Reproduce**
Read the text, click the link.

**Expected behavior**
A clear and concise agreement that states what the user needs to agree to and why.

**Screenshots**
–

**iPhone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 14.5
 - Mercury: v2021.4(54)

**Additional context**
I generally think that usage restrictions for software are a slippery slope and can recommend the following article on the topic: https://www.fsf.org/bulletin/2019/fall/building-ethical-software-based-on-the-four-freedoms .

**Comment by dNitza** [comment]
Hey @wadoli, thanks for reaching out.

That article is definitely interesting. The original intent of the agreement was to: 
1) Let the person using the software know that there are rules relating to their instance that they need to follow and that there may be consequences for harassment or abuse. I don't think violates the first freedom — you can use the software however you like, but don't be surprised when someone shows you the door if you're being a jerk. This is a consequence on the instance side by the way.

and 2) to respond to a request from AppStore review to highlight said rules and let people know how to respond to abuse.

If those intentions are not coming through clearly, then I will need to revisit the text there.
