### ISSUE TITLE
Replying to a post doesn't keep same security setting

### ISSUE THREAD

**Issue by elenners** [dNitza/mercury-issues#3]
On Mastodon web, when replying to a post, the reply maintains the same security setting. Within the app I noticed that in replying to a followers-only post, my reply defaulted to public and I had to switch it to followers-only.

**Comment by dNitza** [comment]
🙏 thanks for this! I have this in an update along with the follow requests stuff that I should get out to Apple for review this evening :)

**Comment by dNitza** [comment]
Should be resolved in the latest update :)
