### ISSUE TITLE
Show Whether User Follows You

### ISSUE THREAD

**Issue by RobATX** [dNitza/mercury-issues#30]
**Is your feature request related to a problem? Please describe.**
User profile doesn't show me if they are following me. 

**Describe the solution you'd like**
Display a follow status line showing whether users follows you. Could be text or icon. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dNitza** [comment]
### A couple of changes that'll come with the next release.

An icon showing you if someone follows you:
![follows-you](https://user-images.githubusercontent.com/479627/201305905-f5ef21f1-3058-465c-bcec-2c488f6a4d24.png)

Or if they don't:
![no-follow-back](https://user-images.githubusercontent.com/479627/201305916-92abad63-6d94-46a7-9349-56d83c51edf1.png)

**Comment by RobATX** [comment]
Fantastico! Thank you!
