### ISSUE TITLE
Feature request: Improve visibility of notification types

### ISSUE THREAD

**Issue by ramsey** [dNitza/mercury-issues#4]
It is difficult to tell the difference between follows, favorites, boosts, and replies in the notifications list. Please provide a clearer visual distinction between these types.

**Comment by dNitza** [comment]
Hey @ramsey yeah that makes sense! I think perhaps some iconography / colours should help with this. I'll try get this out with the next update :)

**Comment by dNitza** [comment]
Have added these to the latest update :)

**Comment by ramsey** [comment]
Thanks so much for the quick response!
