### ISSUE TITLE
VoiceOver treating links as tripple elements

### ISSUE THREAD

**Issue by rkingett** [dNitza/mercury-issues#5]
Links, within profiles, appear as three, back to back, identical elements, rather than just one link.

**To Reproduce**

1. Start VoiceOver.
2. Navigate to a users profile.
3. Swipe right to the profile tags and links/lists. Swipe right and left through the profile elements.

**Expected behavior**
VoiceOver should only identify the link as a single link element. .

**iPhone (please complete the following information):**
 - Device: [iPhone SE 2020]
 - OS: [13.6]

This also applies when using a Bluetooth keyboard.

**Comment by dNitza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐛 VoiceOver treating links as triple elements](https://trello.com/c/LOEq08yI/20-%F0%9F%90%9B-voiceover-treating-links-as-triple-elements)

**Comment by dNitza** [comment]
This one should be fixed now :) For future reference, the issue was that longer URLs would be split over a number of lines, voice over would read the whole URL for each line.
