### ISSUE TITLE
iPhone SE 2016 cannot compose toots

### ISSUE THREAD

**Issue by jasikpark** [dNitza/mercury-issues#7]
**Describe the bug**

The compose view is too cluttered when replying and "you're replying to x" covers everything i'm typing. 

**To Reproduce**
Steps to reproduce the behaviour:

Reply to a toot on iPhone SE 2016 especially to a user with a long username. 

**Expected behavior**

Reply to a toot on iPhone SE 2016 especially to a user with a long username. 

**Screenshots**

![image](https://user-images.githubusercontent.com/10626596/87846425-52059000-c895-11ea-8228-7dbed1df10db.png)

**iPhone (please complete the following information):**

iPhone SE 2016
iOS 13.6

**Additional context**

**Comment by dNitza** [comment]
Hey @jasikpark !

Thanks for the report :) I've adjusted the compose screen to reduce clutter around the text area and to fix the issue with the "replying to..." section overlapping the last few lines of the text area. 

This should be out in the next update which is currently waiting for App Store review.

Cheers,
Dan

![Simulator Screen Shot - iPhone SE (1st generation) - 2020-07-18 at 20 01 41](https://user-images.githubusercontent.com/479627/87850291-50d67080-c932-11ea-9cc6-1e92a46ea8fb.png)

**Comment by jasikpark** [comment]
sounds great!

**Comment by dNitza** [comment]
Addressed in 1.3.1
