### ISSUE TITLE
VoiceOver says no new content after refreshing.

### ISSUE THREAD

**Issue by rkingett** [dNitza/mercury-issues#9]
After a timeline loads, VoiceOver announces that there is no new content when there, in fact, is new content.

## To Reproduce

1. Run VoiceOver.
2. Refresh any timeline after new content arrives.

## Expected behavior

VoiceOver should say, new content available.

## iPhone information.

Device: iPhone 2020.

OS: 13.6.

**Comment by dNitza** [comment]
Ohhh! I think I can see the bug :) I am just about to push out another beta with some more voiceover things so I will include this in it.

**Comment by rkingett** [comment]
Yup, this is fixed. Maybe this should be closed?
